title: Curso de Github Pages
author: Joel Francisco Escobar Socas
email: alu0101130408@ull.edu.es
description: > # this means to ignore newlines until "baseurl:"
  En este  sitio web lo que se hará será dar una breve información acerca de Github Pages con Jekyll y requisitos mínimos.
# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
